# Generated by Django 3.2.6 on 2022-05-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xoki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='creado_por_el_habitante',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='creado_por_el_habitante',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='creado_por_el_habitante',
        ),
        migrations.DeleteModel(
            name='Tipo_de_reporte',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='creado_por_el_habitante',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
