# Generated by Django 3.2.6 on 2022-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xoki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='nombre',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
